# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51620ad7dbc8dd9a318abca0e7b03f58f8e2dff0db29be09d07d89771cfffb1d35e462a79e1f738835a9082ead2b14a0ada0f578a8005d88639753517edf442c

test:
  secret_key_base: 80acf6746d823fb19e965f9106adf0a04eaae02ee0640f0b4780e682e1c10aa7a6da3c643dd99d5a9f37b97cdf628b1c78501b78189f98d4ccfa059963ffb1df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
